import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers/providers";
import { MainLayout } from "@/components/layout/main-layout";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen`}>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
